[package]
name = "docuum"
version = "0.12.0"
authors = ["Stephan Boyer <stephan@stephanboyer.com>"]
edition = "2018"
description = "LRU eviction of Docker images"
license = "MIT"
documentation = "https://github.com/stepchowfun/docuum"
homepage = "https://github.com/stepchowfun/docuum"
repository = "https://github.com/stepchowfun/docuum"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
bollard = "0.7.2"
byte-unit = "3.0"
chrono = "0.4"
colored = "1"
dirs = "1"
env_logger = "0.6"
log = "0.4"
serde_yaml = "0.8"

[dependencies.clap]
version = "2"
features = ["wrap_help"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "0.2"
features = ["macros", "time"]

[package.metadata.rpm]
package = "docuum"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
docuum = { path = "/usr/bin/docuum" }

[package.metadata.rpm.files]
"scripts/docuum.service" = { path = "/usr/lib/systemd/system/docuum.service" }
